language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    - composer self-update
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    # Install dependencies
    - travis_retry composer install --no-progress --prefer-dist

script:
    - make tests

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
    directories:
        - $HOME/.composer/cache